-- =============================================================
-- DataBites - SQL Database Schema
-- Author: Caroline Sholar (Database & QA Lead)
-- Description: Full schema covering all 5 PBIs
--   PBI #1 - User accounts & password reset
--   PBI #2 - Food logging
--   PBI #3 - Meal context (mood, notes, meal type)
--   PBI #4 - Habit summaries (cached)
--   PBI #5 - Log history, edit/delete, undo via soft delete
-- =============================================================

-- -------------------------------------------------------------
-- TABLE: users
-- PBI #1 - Account creation and login
-- -------------------------------------------------------------
CREATE TABLE users (
    user_id       INTEGER  PRIMARY KEY AUTOINCREMENT,
    username      TEXT     NOT NULL UNIQUE,
    email         TEXT     NOT NULL UNIQUE,
    password_hash TEXT     NOT NULL,
    display_name  TEXT,                         -- optional nickname
    profile_pic   TEXT,                         -- optional image path/URL
    created_at    DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Auto-update updated_at when a user row is modified
CREATE TRIGGER trg_users_updated_at
AFTER UPDATE ON users
FOR EACH ROW
BEGIN
    UPDATE users SET updated_at = CURRENT_TIMESTAMP WHERE user_id = OLD.user_id;
END;


-- -------------------------------------------------------------
-- TABLE: food_logs
-- PBI #2 - Logging food entries
-- PBI #3 - Meal context: meal_type, mood, notes
-- PBI #5 - Soft delete: deleted_at enables undo without data loss
-- -------------------------------------------------------------
CREATE TABLE food_logs (
    log_id       INTEGER  PRIMARY KEY AUTOINCREMENT,
    user_id      INTEGER  NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    food_name    TEXT     NOT NULL,
    logged_at    DATETIME NOT NULL,             -- date + time of the meal
    meal_type    TEXT     CHECK(meal_type IN ('breakfast', 'lunch', 'dinner', 'snack', 'other')),
    mood         TEXT     CHECK(mood IN ('happy', 'stressed', 'tired', 'neutral', 'sad', 'excited')), -- PBI #3 mood dropdown
    notes        TEXT,                          -- optional context e.g. "out with friends"
    deleted_at   DATETIME DEFAULT NULL,         -- NULL = active, timestamp = soft-deleted (enables undo)
    created_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME DEFAULT CURRENT_TIMESTAMP
    -- NOTE: No calorie or nutrition fields — intentional per PBI #2 confirmation
);

-- Auto-update updated_at when a food_log row is modified
CREATE TRIGGER trg_food_logs_updated_at
AFTER UPDATE ON food_logs
FOR EACH ROW
BEGIN
    UPDATE food_logs SET updated_at = CURRENT_TIMESTAMP WHERE log_id = OLD.log_id;
END;


-- -------------------------------------------------------------
-- TABLE: food_log_audit
-- PBI #5 - Full change history for every create/edit/delete
--          Enables undo, timestamps of last change, and history view
-- NOTE: log_id has no FK constraint intentionally — audit records
--       must persist even after the original log is hard-deleted.
-- -------------------------------------------------------------
CREATE TABLE food_log_audit (
    audit_id    INTEGER  PRIMARY KEY AUTOINCREMENT,
    log_id      INTEGER  NOT NULL,              -- references food_logs.log_id (no FK by design — see note above)
    user_id     INTEGER  NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    action      TEXT     NOT NULL CHECK(action IN ('create', 'edit', 'delete', 'restore')), -- 'restore' covers undo
    -- Full snapshot of the row at the time of the change
    food_name   TEXT,
    logged_at   DATETIME,
    meal_type   TEXT,
    mood        TEXT,
    notes       TEXT,
    changed_at  DATETIME DEFAULT CURRENT_TIMESTAMP
);


-- -------------------------------------------------------------
-- TABLE: summaries
-- PBI #4 - Cached habit summaries (weekly / monthly)
--          Generated by the Insights Service and stored here
--          to avoid recomputing on every page load.
--          Invalidated and regenerated when food_logs are modified.
-- -------------------------------------------------------------
CREATE TABLE summaries (
    summary_id     INTEGER  PRIMARY KEY AUTOINCREMENT,
    user_id        INTEGER  NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    period_type    TEXT     NOT NULL CHECK(period_type IN ('weekly', 'monthly')),
    period_start   DATE     NOT NULL,           -- e.g. 2026-03-02 for a weekly summary
    period_end     DATE     NOT NULL,           -- e.g. 2026-03-08
    total_entries  INTEGER  DEFAULT 0,          -- total food logs in this period
    most_common_meal_type TEXT,                 -- e.g. 'breakfast'
    most_common_mood      TEXT,                 -- e.g. 'neutral'
    days_logged    INTEGER  DEFAULT 0,          -- how many unique days had at least one log
    summary_notes  TEXT,                        -- auto-generated plain-text summary blurb
    generated_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- Prevent duplicate summaries for the same user + period
    UNIQUE(user_id, period_type, period_start)
);


-- -------------------------------------------------------------
-- TABLE: password_reset_tokens
-- PBI #1 - Password reset feature
-- -------------------------------------------------------------
CREATE TABLE password_reset_tokens (
    token_id    INTEGER  PRIMARY KEY AUTOINCREMENT,
    user_id     INTEGER  NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token       TEXT     NOT NULL UNIQUE,
    expires_at  DATETIME NOT NULL,
    used        INTEGER  DEFAULT 0              -- 0 = unused, 1 = used
);


-- =============================================================
-- INDEXES
-- Improves query performance for common access patterns
-- =============================================================

-- food_logs: filter by user, sort/filter by date
CREATE INDEX idx_food_logs_user_id        ON food_logs(user_id);
CREATE INDEX idx_food_logs_logged_at      ON food_logs(logged_at);

-- food_logs: filter active (non-deleted) entries efficiently
CREATE INDEX idx_food_logs_deleted_at     ON food_logs(deleted_at);

-- audit: look up all changes for a specific log entry or user
CREATE INDEX idx_audit_log_id             ON food_log_audit(log_id);
CREATE INDEX idx_audit_user_id            ON food_log_audit(user_id);

-- summaries: look up cached summaries by user + period
CREATE INDEX idx_summaries_user_period    ON summaries(user_id, period_type, period_start);

-- password reset: look up token quickly for validation
CREATE INDEX idx_reset_tokens_token       ON password_reset_tokens(token);


-- =============================================================
-- USEFUL VIEWS
-- Pre-built queries the backend can use directly
-- =============================================================

-- Active food logs only (excludes soft-deleted entries)
-- Use this for: history page, summary generation, habit insights
CREATE VIEW active_food_logs AS
SELECT
    log_id,
    user_id,
    food_name,
    logged_at,
    meal_type,
    mood,
    notes,
    created_at,
    updated_at
FROM food_logs
WHERE deleted_at IS NULL;


-- Most recent audit entry per log (shows last change timestamp)
-- Use this for: displaying "last edited" timestamps in the history page (PBI #5)
CREATE VIEW latest_audit_per_log AS
SELECT
    log_id,
    user_id,
    action      AS last_action,
    changed_at  AS last_changed_at
FROM food_log_audit
WHERE audit_id IN (
    SELECT MAX(audit_id)
    FROM food_log_audit
    GROUP BY log_id
);
